server:
  port: 8080




spring:
  mandatory-file-encoding=: UTF-8
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver

